all:	cw_binary cw_multiclass

cw_multiclass:
	g++ -o bin/cw_multiclass_learn  src/cw_multiclass_learn.cpp
	g++ -o bin/cw_multiclass_classify  src/cw_multiclass_classify.cpp

cw_binary:
	g++ -o bin/cw_binary_learn  src/cw_binary_learn.cpp
	g++ -o bin/cw_binary_classify src/cw_binary_classify.cpp



