tweetSegment:tweetSegment.cpp util.cpp util.h segmenter.cpp segmenter.h extraResource.cpp extraResource.h Headers.h
	g++ tweetSegment.cpp util.cpp segmenter.cpp extraResource.cpp -o tweetSegment

clean:
	rm -rf *.o tweetSegment
